  - name: Configuring the  Redis Repository
    ansible.builtin.copy:
      src: redis.repo
      dest: /etc/yum.repos.d/redis.repo

  - name: Installing redis 
    ansible.builtin.package:
     name: redis-6.2.11
     state: present 



  - name: Updating the redis config to be public
    ansible.builtin.replace:
     path: /etc/mongod.conf
     regexp: '127.0.0.1'
     replace: '0.0.0.0'

  - name: starting redis
    ansible.builtin.systemd:
      name: redis
      state: started
      enabled: true


  - name: configuring Node name 
    ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}