  - name: Configuring the  mongodb Repository
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: Installing Mongodb 
    ansible.builtin.package:
     name: mongodb-org
     state: present 

# ansible.builtin.replace module – Replace all instances of a particular string in a file using a back-referenced regular expression

  - name: Updating the MongoDB config to be public
    ansible.builtin.replace:
     path: /etc/mongod.conf
     regexp: '127.0.0.1'
     replace: '0.0.0.0'

  - name: starting mongodb
    ansible.builtin.systemd:
      name: mongod
      state: started
      enabled: true


  - name: Download and extracting the MongoDB schema
    ansible.builtin.unarchive:
      src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
      dest: /tmp
      remote_src: yes
#community.mongodb.mongodb_shell module – Run commands via the MongoDB shell.
#
  - name: Injecting the MongoDB Catalogue schema
    community.mongodb.mongodb_shell:
      file: "/tmp/{{COMPONENT}}-main/{{ item }}.js"
      idempotent: yes
    loop:
      - catalogue
      - users



  # - name: Injecting the MongoDB User schema
  #   community.mongodb.mongodb_shell:
  #    file: "/tmp/{{COMPONENT}}-main/users.js"
  #    idempotent: yes
