- name: Demo on using conditions
  hosts: all
  vars: 
    action: false
  tasks:
    - name: Run this task only when the distribution is CentOS
      ansible.builtin.debug:
       msg: I am a CentOS machine
      when: ansible_distribution == "CentOS"

    - name: Run this task only when the distribution is Debian
      ansible.builtin.debug:
       msg: I am a Deban machine
      when: ansible_distribution == "Debian"
    
    - name: Run this action
      ansible.builtin.debug:
       msg: I am learning ansible and I will only print when action is true
      when: action
    