#- name:  Demo on using Erros
- name: Check Tomcat is running or not and start  if it is not running 
  hosts: all
  tasks:
    - name: Cheking Tomcat status
      ansible.builtin.shell: ps -ef | grep  java | grep -v grep
      register: OUT
      ignore_errors: yes

    - name: Starting Tomcat
      ansible.builtin.debug:
        msg: Starting Tomcat
    
    