- name: Demo on using Facts
  hosts: all
  tasks: 
     - name: Printing the facts 
       ansible.builtin.debug:
        msg: ansible distribution is {{ ansible_distribution }}
      
     - name: Printing the macAddress of the machine
       ansible.builtin.debug:
        msg: ansible distribution is {{ ansible_default_ipv4.macaddress }}