- name: Demo on using Facts
  hosts: all
  #gather_facts: false    #using this you can control on gathering the facts
    tasks: 
     - name: Printing the facts 
       ansible.builtin.debug:
        msg: ansible distribution is {{ ansible_distribution }}
      
     - name: Printing the macAddress of the machine
       ansible.builtin.debug:
        msg: macAddress is  {{ ansible_default_ipv4.macaddress }}