-  name: Demo on using Loops
   hosts: all
   tasks:
    - name: Demoo on using loop 1
      ansible.builtin.debug:
       msg: value of the item is 10

    - name: Demoo on using loop 2
      ansible.builtin.debug:
       msg: value of the item is 20

    - name: Demoo on using loop 3
      ansible.builtin.debug:
       msg: value of the item is 30
    