- name:  Demonstrating Previlage escalation
  hosts: all
  become: yes                       # Previlage escalation Runs the playbooks as root user
  tasks:
    - name: Checking the user id
      ansible.builtin.shell: id 
      register: OUT

    - name: Printing the OUT variblae
      ansible.builtin.debug:
        msg: "{{OUT.stdout}}"
    