# - name: Playbook to configure roboshop project
#   hosts: "{{COMPONENT}}"
#   become: yes
#   roles:

#     loop:
#         - "{{ COMPONENT }}"


- name: Playbook to configure roboshop project
  become: yes
  hosts: "{{ COMPONENT }}"
  roles:
    - "{{ COMPONENT }}"
