- name: play1
  hosts: all
  tasks:
    - name: Printing Hello from Play1
      ansible.builtin.debug:
        msg: Haai From play1 of task1

    - name: Printing Hi from Play1
      ansible.builtin.debug:
        msg: Haai  From play1 of task2

- name: play2
  hosts: prod
  tasks:
    - name: Printing Hai from Play2
      ansible.builtin.debug:
        msg: Hello From play2 of task1


# - name: play2
#   hosts: prod
#   task: Hello
#     - name: Ths is a frma
#       ansible.builtin.un