- name:  Playbook to demonstrate template
  hosts: all
  tasks:
    - name: Copying the systemd file
      ansible.builtin.template:
        src: env.txt                  # src always be in the local jenkins server
        dest: /home/centos/env.txt                 # destination has to be a node server
