- name: Demo on using variables on playbooks
  hosts: all
  vars:                           #Global variable: variables can be accessed by all the tasks of the play
    URL: play.google.com
  tasks: 
     - name: Printing value of the variable
       ansible.builtin.debug:
        msg: Value of URL is {{ URL }}

     - name: Demo to show local variable 
        ansible.builtin.debug:  
        msg: Value of URL is {{ URL }}
      vars:  
        URL: task.google.com