- name: Demo on using variables on playbooks
  hosts: all
  vars:                           #Global variable: variables can be accessed by all the tasks of the play
    URL: play.google.com
  tasks: 
    - name: Printing value of the variable
      ansible.builtin.debug:
      msg: value of URL is  {{ URL }}

    - name: Demo to show local variables
      ansible.builtin.debug:
        msg: value of URL is  {{ URL }}
      vars:                                   # local variables 
        URL: play.google.com