- name: Demo on using variables on playbooks
  hosts: all
  vars:                           #Global variable: variables can be accessed by all the tasks of the play
    URL: play.google.com
  vars_files:
    - dev-vars.yaml
  tasks: 
     - name: Printing value of the variable
       ansible.builtin.debug:
        msg: Value of URL is {{ URL }}

     - name: Demo to show the Local variable
       ansible.builtin.debug:
        msg: Value of URL is {{ URL }}
       vars: 
         URL: task.google.com

     - name: Printing the value of the variable which is not declared
       ansible.builtin.debug:
        msg: Value of car is {{ CARNAME }}
       