- name: Demo on using variables on playbooks
  hosts: all
  vars:                           #Global variable: variables can be accessed by all the tasks of the play
    URL: play.google.com
  tasks: 
     - name: Printing Hello from Play1
       ansible.builtin.debug:
        msg: Haai From play1 of task1

    