  - name: Installing nginx 
    ansible.builtin.package:
     name: nginx
     state: present

  - name: Download and extracting the frontend  
    ansible.builtin.include_role:
      name: common
      tasks_from: download
 
 
  - name: Cleanup of old HTML Content
    ansible.builtin.file:
     path: /usr/share/nginx/html/
     state: absent
      

  - name: Copy the frontend Component which is downloaded on the remote machine nginx path
    ansible.builtin.copy:
      src: /tmp/{{COMPONENT}}-main/static/
      dest: /usr/share/nginx/html/
      remote_src: yes


  

# if the source you are trying to copy on the remote machine , ensure to give the remote_src=yes      

  - name: Copying the proxy config
    ansible.builtin.template:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf
    notify: Restarting Nginx 

 #   notify: Retarting Nginx 

  - name : started {{COMPONENT}}
    ansible.builtin.shell: systemctl start nginx

#  - handlers:
#       name: Restart nginx
#       service: name=nginx state=restarted

  - name: Starting {{COMPONENT}}
    ansible.builtin.systemd:
      name: nginx
      state: started
      enabled: true

  # - name: Restarting nginx
  #   ansible.builtin.shell: systemctl start nginx 
      
  # - name: Configuring Node name Repo
  #   ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}