- name: Copying the Logstash config
  ansible.builtin.template:
      src: logstash.conf
      dest: /etc/logstash/conf.d/logstash.conf


- name: Restarting  Logstash
  ansible.builtin.service:
      name: logstash
      state: restarted
      daemon_reload: yes


- name: Wait for logstash port to come in to listening state
  wait_for:
    port: 5044
    delay: 30
    timeout: 60
