
  - name: Configuring Node Js Repo
    ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

  - name: Installing NodeJS
    ansible.builtin.package:
      name: nodejs
      state: present

# Creating a user account in Ansible

  - name: Creating roboshop user account
    ansible.builtin.user:
     name: {{ APPUSER }}
     comment: Roboshop Application user 
    
#   - name: Installing nginx 
#     ansible.builtin.package:
#      name: nginx
#      state: present

#   # - name: Download and extracting the Component
#   #   ansible.builtin.unarchive:
#   #     src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip 
#   #     dest: /tmp
#   #     remote_src: yes
#   - name: Download and Extract frontend 
#     ansible.builtin.include_role:
#      name: common
#      task_from: download
 
#   - name: Cleanup of old HTML Content
#     ansible.builtin.file:
#      path: /usr/share/nginx/html/
#      state: absent
      

#   - name: Copy the frontend Component which is downloaded on the remote machine nginx path
#     ansible.builtin.copy:
#       src: /tmp/{{COMPONENT}}-main/static/
#       dest: /usr/share/nginx/html/
#       remote_src: yes

  

# # if the source you are trying to copy on the remote machine , ensure to give the remote_src=yes      
#   - name: Copying the proxy-config
#     ansible.builtin.copy:
#       src: roboshop.config
#       dest: /etc/nginx/default.d/roboshop.conf
#       remote_src: yes   


#   - name: starting nginx
#     ansible.builtin.systemd:
#       name: nginx
#       state: started
#       enabled: true