# Creating a user account in Ansible

 - name: Creating App user for {{COMPONENT}}-{{ENV}} server
   ansible.builtin.user:
     name: "{{APPUSER}}"
     comment: Roboshop Application user 
   register: OUT

 - name: Just printing the output
   ansible.builtin.debug: 
    msg : "{{OUT}}" 

 - name:  Install bottle into specified (virtualenv) , inheriting globally installed modules
   ansible.builtin.pip:
        name:
        - boto3
        - botocore
        executable: pip3