
 - name: Configuring Node Js Repo for {{COMPONENT}}
   ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

 - name: Installing NodeJS on  {{COMPONENT}}-{{ENV}} server
   ansible.builtin.package:
      name: nodejs
      state: present

# Creating a user account in Ansible

 - name: Creating App user 
   ansible.builtin.include_role:
     name: common
     tasks_from: create_user 

 - name: Downloading the .pem file needed for node js component
   ansible.builtin.get_url:  
      url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem  
      dest: "/home/{{APPUSER}}/global-bundle.pem"
 

 - name: Download and Extracting the {{ COMPONENT }} 
   ansible.builtin.include_role:
     name: common
     tasks_from: download

 - name: Generating artifact with npm install
   community.general.npm:
     path: /home/{{APPUSER}}/{{COMPONENT}}/


 - name: Configuring Service 
   ansible.builtin.include_role:
     name: common
     tasks_from: config_svc

 - name: configuring Node name Repo
   ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}