- name: Installing Python on {{COMPONENT}}-{{ENV}}
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: present


# Creating a user account in Ansible

- name: Creating App user 
  ansible.builtin.include_role:
     name: common
     tasks_from: create_user 

    

- name: Download and Extracting the {{ COMPONENT }} 
  ansible.builtin.include_role:
     name: common
     tasks_from: download


- name: Just Fetching the output
  ansible.builtin.shell: id roboshop
  register: OUTPUT




- name: Ensure SELinux is set to enforcing mode
  winuser
      path: /home/{{APPUSER}}/{{COMPONENT}}/


#  - name: Configuring Service 
#    ansible.builtin.include_role:
#      name: common
#      tasks_from: config_svc

#  - name: configuring Node name Repo
#    ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}